services:
  mongodb:
    image: registry.hub.docker.com/library/mongo
    ports:
      - ${MONGO_PORT_NUMBER:-27017}:${MONGO_PORT_NUMBER:-27017}
    container_name: ${DBHOSTNAME:-mongo}
  express:
    build:
      context: .
      target: release
    ports:
      - ${EXPRESS_PORT_NUMBER:-3000}:${EXPRESS_PORT_NUMBER:-3000}
    depends_on:
      - mongodb
    healthcheck:
      test: 'curl localhost:3000/testcases'
      interval: '30s'
      timeout: '5s'
      start_period: '5s'
      retries: 3
  e2e-tests:
    image: node
    depends_on:
      - express
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ['npm', 'test']
    environment:
      - BASE_URL=http://express:${EXPRESS_PORT_NUMBER:-3000}
