services:
  mongodb:
    image: registry.hub.docker.com/library/mongo
    ports:
      - ${MONGO_PORT_NUMBER}:${MONGO_PORT_NUMBER}
    container_name: ${DBHOSTNAME}
  express:
    build:
      context: .
      target: release
    ports:
      - ${EXPRESS_PORT_NUMBER}:${EXPRESS_PORT_NUMBER}
    depends_on:
      - mongodb
  e2e-tests:
    image: node
    depends_on:
      - express
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ['npm', 'test']
    environment:
      - BASE_URL=http://express:${EXPRESS_PORT_NUMBER}
