services:
  mongodb:
    image: registry.hub.docker.com/library/mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    container_name: ${DBHOSTNAME}
  express:
    image: ${SERVICE_NAME}
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
    depends_on:
      - mongodb
    entrypoint: ['launcher', 'npm run compile && node ./build/src/index.js']
  e2e-tests:
    image: node
    depends_on:
      - express
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ['bash', '-c', 'npm install && npm test']
    environment:
      - BASE_URL=http://express:${EXPRESS_PORT}
