apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: express
  name: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: express
    spec:
      containers:
        - image: express-mongo-service_express
          name: express
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
