apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  labels:
    app: express
spec:
  selector:
    matchLabels:
      app: express
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          image: express-mongo-service_express
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "1G"
              cpu: 1
            limits:
              memory: "2G"
              cpu: 2
