apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mongo
          image: registry.hub.docker.com/library/mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "1G"
              cpu: 1
            limits:
              memory: "2G"
              cpu: 2
